#YAML file for defining the secret "db-creds":

apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  username: cm9vdF91c2Vy      # base64 encoded value of "root_user"
  password: RXhwZXJ0cyExMjM=  # base64 encoded value of "Experts!123"
  url: bXlzcWwuc2VydmljZXM=   # base64 encoded value of "mysql.services.com"
