# YAML file for deploying an NGINX pod that mounts the secrets:
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: secret-volume
      secret:
        secretName: db-creds
